# Publish the latest version of master to gh-pages branch
#
name: update-gh-pages-branch
on:
  pull_request:
    branches:
#      - master
      - dev-code-branch
    paths:
      - helm-repos
      - README.md
#
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/Checkout@v2.0.0
#
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.5.7
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: helm-repos # The folder the action should deploy.
